### ISSUE TITLE
Build failure when trying to build freetoolbox

### ISSUE THREAD

**Issue by neoclust** [FreeHealth/freehealth#98]
mainwindow.cpp: In member function 'virtual void Core::MainWindow::extensionsInitialized()':
mainwindow.cpp:183:116: error: 'THE_FREEMEDFORMS_COMMUNITY' is not a member of 'Trans::Constants'
     setWindowTitle(QString("%1 %2 - (c) %3").arg(qApp->applicationName()).arg(qApp->applicationVersion()).arg(tkTr(Trans::Constants::THE_FREEMEDFORMS_COMMUNITY)));
                                                                                                                    ^

**Comment by jeromecc** [comment]
Thanks for the bug report.
This is fixed with 01295ecb18bf910b04d50f3cd35606e5b4477862
Unfortunately, those accessory apps contain numerous other bugs that prevent building them and need to be renamed to respect FreeMedForms copyright.
The renaming needs to be done here, upstream.
I suggest buildind only the main package "freehealth ehr" that corresponds to freehealth.pro for the time being.
I will work on the prescription module ASAP because other people outside of FreeHealth project are interested in using it.
To the best of my knowledge, the others modules are not used by anyone outside of FreeHealth developers. I don't think it should be a priority for the project right know, but of course, if we receive fixes for these modules, we will gladly merge them!
Thanks again for your packaging efforts for Mageia and for your bug reports.
